In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [7]:
df = pd.read_csv("ks-projects-201801.csv")
df

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378656,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17,50000.0,2014-09-17 02:35:30,25.0,canceled,1,US,25.0,25.0,50000.00
378657,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19,1500.0,2011-06-22 03:35:14,155.0,failed,5,US,155.0,155.0,1500.00
378658,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16,15000.0,2010-07-01 19:40:30,20.0,failed,1,US,20.0,20.0,15000.00
378659,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13,15000.0,2016-01-13 18:13:53,200.0,failed,6,US,200.0,200.0,15000.00
378660,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16,2000.0,2011-07-19 09:07:47,524.0,failed,17,US,524.0,524.0,2000.00

In [14]:
def load_and_process(url):
    df1 = (
        pd.read_csv(url)
        .dropna()
        .assign(GoalReachedPercentage = lambda x: x["pledged"] / x["goal"] * 100)
        .sort_values("GoalReachedPercentage", ascending = False)
        .reset_index(drop=True)
    )
    return df1

In [17]:
df = load_and_process("ks-projects-201801.csv")
df

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,GoalReachedPercentage
0,9509582,VULFPECK /// The Beautiful Game,Music,Music,USD,2016-10-17,1.0,2016-08-18 09:04:03,104277.89,successful,3917,US,23874.13,104277.89,1.00,10427789.0
1,1947298033,Re-covering with Friends,Rock,Music,USD,2016-12-13,1.0,2016-10-14 19:04:27,68764.10,successful,955,US,9306.00,68764.10,1.00,6876410.0
2,907870443,VULFPECK /// Thrill of the Arts,Music,Music,USD,2015-10-09,1.0,2015-08-10 19:31:56,55266.57,successful,1673,US,55266.57,55266.57,1.00,5526657.0
3,1388400809,Energy Hook,Video Games,Games,USD,2013-06-10,1.0,2013-05-10 01:22:38,41535.01,successful,1622,US,41535.01,41535.01,1.00,4153501.0
4,1413857335,Band of Brothers 2nd Chance,Tabletop Games,Games,USD,2016-08-02,1.0,2016-07-12 00:29:12,32843.00,successful,268,US,26095.00,32843.00,1.00,3284300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374855,493272583,Bite O' BlueÂ® (Canceled),Food,Food,USD,2012-02-15,38000.0,2011-12-17 02:46:31,0.00,canceled,0,US,0.00,0.00,38000.00,0.0
374856,493244824,Funny Video About Emigration,Music Videos,Film & Video,GBP,2014-08-11,600.0,2014-07-12 07:52:00,0.00,failed,0,GB,0.00,0.00,1001.40,0.0
374857,493224232,Secret Kickstarter Project (Canceled),Technology,Technology,EUR,2014-08-16,5000.0,2014-07-17 01:18:13,0.00,canceled,0,NL,0.00,0.00,6633.50,0.0
374858,493218174,Do It Yourself Wood Projects and Art,Public Art,Art,USD,2015-11-21,35000.0,2015-10-16 22:49:49,0.00,failed,0,US,0.00,0.00,35000.00,0.0
374859,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.00,failed,0,GB,0.00,0.00,1533.95,0.0

In [19]:
df.describe(include=[np.number]).T

,count,mean,std,min,25%,50%,75%,max
ID,374860.0,1.074652e+09,6.191368e+08,5971.00,5.380633e+08,1.075289e+09,1.610137e+09,2.147476e+09
goal,374860.0,4.952299e+04,1.189362e+06,0.01,2.000000e+03,5.500000e+03,1.650000e+04,1.000000e+08
pledged,374860.0,9.750538e+03,9.601094e+04,0.00,3.100000e+01,6.200000e+02,4.080000e+03,2.033899e+07
backers,374860.0,1.066884e+02,9.117101e+02,0.00,2.000000e+00,1.200000e+01,5.700000e+01,2.193820e+05
usd pledged,374860.0,7.036802e+03,7.864016e+04,0.00,1.698000e+01,3.947650e+02,3.034425e+03,2.033899e+07
usd_pledged_real,374860.0,9.120899e+03,9.131969e+04,0.00,3.100000e+01,6.244950e+02,4.050895e+03,2.033899e+07
usd_goal_real,374860.0,4.586303e+04,1.158767e+06,0.01,2.000000e+03,5.500000e+03,1.600000e+04,1.663614e+08
GoalReachedPercentage,374860.0,3.262893e+02,2.682482e+04,0.00,4.571429e-01,1.342000e+01,1.065281e+02,1.042779e+07

In [20]:
df.describe(exclude=[np.number]).T

                count  unique                       top    freq
name           374860  372068  New EP/Music Development      13
category       374860     159            Product Design   22310
main_category  374860      15              Film & Video   62696
currency       374860      14                       USD  292624
deadline       374860    3164                2014-08-08     702
launched       374860  374298       1970-01-01 01:00:00       7
state          374860       5                    failed  197611
country        374860      22                        US  292624

In [18]:
import pandas_profiling
from pandas_profiling import ProfileReport

prof = ProfileReport(df)
prof.to_file(output_file='output.html')

HBox(children=(FloatProgress(value=0.0, description='Summarize dataset', max=30.0, style=ProgressStyle(descripâ€¦

HBox(children=(FloatProgress(value=0.0, description='Generate report structure', max=1.0, style=ProgressStyle(â€¦

HBox(children=(FloatProgress(value=0.0, description='Render HTML', max=1.0, style=ProgressStyle(description_wiâ€¦

HBox(children=(FloatProgress(value=0.0, description='Export report to file', max=1.0, style=ProgressStyle(descâ€¦